#!/usr/bin/bash

dladm create-etherstub stub0
dladm create-vnic -l stub0 vnic0
ipadm create-if vnic0
ipadm create-addr -T static -a 10.0.0.1/24 vnic0/static
echo 'map e1000g0 10.0.0.0/24 -> 0.0.0.0/32' | ipnat -f -
