#!/usr/bin/bash

dladm create-etherstub stub0
dladm create-vnic -l stub0 vnic0
ipadm create-if vnic0
ipadm create-addr -T static -a <gz_addr> vnic0/static

echo 'map e1000g0 <zone_network> -> 0.0.0.0/32' | ipnat -f -

# When we SSH into port 2222, ensure that that goes to 22 in the GZ
# and is never forwarded to the zone.
echo 'rdr e1000g0 0.0.0.0/0 port 2222 -> <gz_ip> port 22' | ipnat -f -

routeadm -u -e ipv4-forwarding
routeadm -u -e ipv4-routing
